# Generated by Django 3.2 on 2021-05-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(choices=[('automation', 'automation'), ('ROS', 'ROS'), ('microcontroller', 'microcontroller')], default='automation', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='thought',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='anon', max_length=20),
        ),
    ]
