# Generated by Django 3.2 on 2021-05-24 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210524_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='two_line_des',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='thought',
            field=models.CharField(default='Notice me senpai', max_length=200),
        ),
    ]
