# Generated by Django 3.2 on 2021-05-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blog_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_name',
        ),
    ]
