# Generated by Django 3.2 on 2021-05-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='you@tube.com', max_length=254),
            preserve_default=False,
        ),
    ]
