# Generated by Django 3.2 on 2021-05-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cat',
            field=models.CharField(choices=[('Robotics', 'user-interface'), ('Web', 'branding'), ('Microcontroller', 'mockup'), ('Photograpy', 'ui')], default='ui', max_length=20),
        ),
    ]
