# Generated by Django 3.2 on 2021-05-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cat',
            field=models.CharField(choices=[('user-interface', 'Robotics'), ('branding', 'Web'), ('mockup', 'Microcontroller'), ('ui', 'Photograpy')], default='ui', max_length=20),
        ),
    ]
