# Generated by Django 3.2 on 2021-05-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210524_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/images/')),
                ('pdf', models.FileField(upload_to='portfolio/pdf')),
            ],
        ),
    ]
