# Generated by Django 3.2 on 2021-05-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='catc',
            field=models.CharField(choices=[('user-interface', 'Robotics'), ('branding', 'Web'), ('mockup', 'Microcontroller'), ('ui', 'Photograpy')], default='ui', max_length=20),
        ),
    ]
