# Generated by Django 3.2 on 2021-05-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_certificate_catc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='catc',
            field=models.CharField(choices=[('user-interface', 'Robotics'), ('branding', 'Web'), ('mockup', 'IOT'), ('ui', 'AI')], default='ui', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='cat',
            field=models.CharField(choices=[('user-interface', 'Robotics'), ('branding', 'Web'), ('mockup', 'Microcontroller'), ('ui', 'Photograpy'), ('mis', 'Miscellaneous')], default='ui', max_length=20),
        ),
    ]
