# Generated by Django 3.2 on 2021-05-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210525_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='catc',
            field=models.CharField(choices=[('user-interface', 'Robotics'), ('branding', 'Web'), ('mockup', 'IOT'), ('ui', 'AI'), ('mis', 'Miscellaneous')], default='ui', max_length=20),
        ),
    ]
