# Generated by Django 3.2 on 2021-05-26 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment_email'),
        ('portfolio', '0010_alter_certificate_catc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_blog', to='blog.blog'),
        ),
    ]
