# Generated by Django 3.2 on 2021-05-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_project_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='post',
        ),
    ]
