# Generated by Django 3.2.3 on 2021-05-29 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_project_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='date_of_completion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_of_completion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
