# Generated by Django 3.2.3 on 2021-05-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20210529_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='catc',
            field=models.CharField(choices=[('user-interface', 'Robotics'), ('branding', 'Web'), ('mockup', 'IOT'), ('ui', 'AI'), ('mis', 'Miscellaneous'), ('par', 'Participation')], default='ui', max_length=20),
        ),
    ]
