# Generated by Django 3.2 on 2021-06-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_certificate_catc'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='priority_number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=4),
            preserve_default=False,
        ),
    ]
